# Backtesting Configuration

# Data settings
data:
  filepath: "/Users/martinshih/Downloads/Systematic/Candlestick_Data/MES_Data/U19_H25.csv"
  date_column: "datetime"
  datetime_format: null  # Use null for auto-detection
  data_type: "mes_futures"  # Add this to specify data type

# Validation settings
validation:
  # In-sample optimization
  insample:
    train_start: "2023-01-01"
    train_end: "2023-12-31"
    objective_function: "profit_factor"  # Options: profit_factor, sharpe_ratio, calmar_ratio

  # In-sample permutation test
  insample_test:
    n_permutations: 1000
    show_plot: true

  # Walk-forward optimization
  walkforward:
    train_window: "3M"  # 3-month training window
    train_interval: "5D"  # Re-optimize every 5 days
    show_optimization_progress: true

  # Walk-forward permutation test
  walkforward_test:
    train_data_start: "2023-01-01"
    train_data_end: "2023-03-31"
    test_data_start: "2023-04-01"
    test_data_end: "2023-05-31"
    n_permutations: 200
    show_plot: true

# Strategy settings
strategies:
  donchian_breakout:
    description: "Donchian Channel Breakout strategy"
    default_params:
      lookback: 20
    parameter_grid:
      lookback:
        range:
          start: 10
          end: 100
          step: 5
  
  moving_average_crossover:
    description: "Moving Average Crossover strategy"
    default_params:
      fast_period: 10
      slow_period: 50
    parameter_grid:
      fast_period:
        range:
          start: 5
          end: 50
          step: 5
      slow_period:
        range:
          start: 20
          end: 200
          step: 10

  morning_reversal:
    description: "Morning Reversal strategy based on Bollinger Bands, VWAP, and candlestick patterns"
    default_params:
      bb_period: 20
      bb_std: 2.0
      atr_period: 14
      stop_atr_multiplier: 1.5
      risk_per_trade: 0.01
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      atr_min_threshold: 0.8
      atr_max_threshold: 2.0
    parameter_grid:
      bb_period:
        range:
          start: 10
          end: 30
          step: 5
      bb_std:
        values: [ 1.5, 2.0, 2.5 ]
      atr_period:
        values: [ 10, 14, 20 ]
      stop_atr_multiplier:
        values: [ 1.0, 1.5, 2.0 ]
      rsi_oversold:
        values: [ 20, 30, 40 ]
      rsi_overbought:
        values: [ 60, 70, 80 ]
      atr_min_threshold:
        values: [ 0.7, 0.8, 0.9 ]
      atr_max_threshold:
        values: [ 1.5, 2.0, 2.5 ]
    bullish_patterns:
      values: [
        'hammer',
        'engulfing',
        'morning_star',
        'piercing_line',
        'three_white_soldiers',
        'three_outside_up',
        'morning_doji_star'
      ]
    bearish_patterns:
      values: [
        'shooting_star',
        'engulfing',
        'evening_star',
        'dark_cloud_cover',
        'three_black_crows',
        'three_line_strike_bullish'
      ]

# Output settings
output:
  save_results: true
  results_dir: "results"
  plot_results: true

